from enum import Enum


class ErrorCode(str, Enum):
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    NOT_FOUND = "NOT_FOUND"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    CONFLICT = "CONFLICT"
    BAD_REQUEST = "BAD_REQUEST"
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    AUTH_FAILED = "AUTH_FAILED"
    CORPUS_NOT_READY = "CORPUS_NOT_READY"
    LLM_NOT_CONFIGURED = "LLM_NOT_CONFIGURED"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    INVALID_FILE_TYPE = "INVALID_FILE_TYPE"
    PERSISTENCE_ERROR = "PERSISTENCE_ERROR"


class IntentType(str, Enum):
    LOOKUP = "lookup"
    COMPARE = "compare"
    TREND = "trend"
    SUMMARIZE = "summarize"
    METRIC = "metric"
    GENERAL = "general"
